media_folder: "images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Notícias"
    files:
      - file: "content/noticias.json"
        label: "Notícias"
        name: "noticias"
        format: "json"
        fields:
          - label: "Lista"
            name: "items"
            widget: "list"
            fields:
              - label: "Esporte"
                name: "sport"
                widget: "string"
              - label: "Título"
                name: "titulo"
                widget: "string"
              - label: "Resumo"
                name: "resumo"
                widget: "text"
              - label: "Tempo"
                name: "tempo"
                widget: "string"
              - label: "Imagem"
                name: "imagem"
                widget: "image"
                required: false
